-- ── Sprint 14 Migration ──────────────────────────────────────────────────────
-- Follow-Up Rotation System + AI Processing + Production Readiness columns
-- Run in Supabase SQL Editor

-- ── Aftercare: follow-up rotation + AI processing columns ────────────────────

ALTER TABLE aftercare
  ADD COLUMN IF NOT EXISTS followup_template_used      text,          -- A / B / C / D / E
  ADD COLUMN IF NOT EXISTS ai_summary                  text,          -- generated by followup-processor
  ADD COLUMN IF NOT EXISTS followup_processor_output   jsonb,         -- full structured processor output
  ADD COLUMN IF NOT EXISTS practitioner_alert          boolean DEFAULT false; -- urgent flag for Daron

-- ── Clients: outcome intelligence columns ────────────────────────────────────

ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS last_checkin_at        timestamptz,
  ADD COLUMN IF NOT EXISTS last_intensity_score   integer,
  ADD COLUMN IF NOT EXISTS practitioner_alert     boolean DEFAULT false;

-- ── Indexes for dashboard queries ────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_aftercare_template_used
  ON aftercare (followup_template_used);

CREATE INDEX IF NOT EXISTS idx_aftercare_practitioner_alert
  ON aftercare (practitioner_alert)
  WHERE practitioner_alert = true;

CREATE INDEX IF NOT EXISTS idx_clients_practitioner_alert
  ON clients (practitioner_alert)
  WHERE practitioner_alert = true;
