import {escapeHTML as E,date,time} from './model.mjs';
export async function call(path,method='GET',body){const r=await fetch('/.netlify/functions/'+path,{method,credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const result=await r.json();if(!r.ok)throw Error(result.error||'Request was not accepted.');return result;}
export function securityCard(info,enabled){return `<section class="panel panel-body section-gap"><h2>Security</h2><p>Signed in as Daron · ${E(info?.session_status||'Session active')}</p><p>Last credential change: ${info?.password_changed_at?E(date(info.password_changed_at)):'Initial credential · change date not recorded'}</p><p>${info?.security_review_recommended?'Security review recommended':('Security review due: '+(info?.security_review_due_at?E(date(info.security_review_due_at)):'Not available'))}</p><button data-security-change ${enabled?'':'disabled'}>Change Password/PIN</button><p class="muted">Change it whenever you choose. We recommend a security review every 180 days; changes are not forced.</p></section>`;}
export async function manage(session){const data=await call('sessions?id='+encodeURIComponent(session.id)+'&action=manage-link');const url=new URL(data.url);if(url.origin!==location.origin||url.pathname!=='/manage-appointment.html'||!url.searchParams.get('token')||url.searchParams.get('session_id')!==session.id)throw Error('A valid signed appointment link was not returned.');location.assign(url.href);}
export function appointmentAction(action,session,openDialog,onChanged){
 const summary=`<p><strong>${E(session.client_name)}</strong><br>${E(session.service||'Service not recorded')}<br>${E(date(session.session_date))} · ${E(time(session.session_time))} Eastern</p>`;
 const requestId=crypto.randomUUID();
 const perform=(values)=>{openDialog(action==='Cancel'?'Confirm cancellation':'Confirm reschedule',summary+(action==='Reschedule'?`<p>New appointment: <strong>${E(date(values.new_date))} · ${E(time(values.new_time))} Eastern</strong></p>`:'')+`<p>This changes this appointment and its availability. Calendar and eligible client notices will follow the normal workflow. No refund is issued here.</p><form id="confirm-appointment"><button type="submit" class="gold">${action==='Cancel'?'Confirm cancellation':'Confirm reschedule'}</button><button type="button" data-close>Keep appointment unchanged</button><p role="alert" id="action-error"></p></form>`);
  document.querySelector('#confirm-appointment').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{await call('sessions?id='+encodeURIComponent(session.id),'PATCH',{p1:true,action:action.toLowerCase(),confirmed:true,request_id:requestId,expected_date:session.session_date,expected_time:session.session_time,...values});document.querySelector('#detail').close();await onChanged();}catch(e){document.querySelector('#action-error').textContent=e.message;button.disabled=false;}});
 };
 if(action==='Cancel'){perform({});return;}
 openDialog('Reschedule appointment',summary+`<form id="choose-appointment"><label>New date · Eastern<input name="new_date" type="date" required></label><label>New time · Eastern<input name="new_time" type="time" step="900" required></label><p class="muted">The Schedule display time zone does not change these Eastern booking inputs.</p><button type="submit">Review change</button><button type="button" data-close>Back</button></form>`);
 document.querySelector('#choose-appointment').addEventListener('submit',event=>{event.preventDefault();perform(Object.fromEntries(new FormData(event.target)));});
}
export function changeCredential(openDialog,onChanged){openDialog('Change your password',`<p>Use at least 12 characters. Saving signs out every existing dashboard session.</p><form id="change-credential"><label>Current password/PIN<input type="password" name="current" autocomplete="current-password" maxlength="256" required></label><label>New password<input type="password" name="next" autocomplete="new-password" minlength="12" maxlength="256" required></label><label>Confirm new password<input type="password" name="confirm" autocomplete="new-password" minlength="12" maxlength="256" required></label><button type="submit" class="gold">Change password and sign out</button><button type="button" data-close>Keep current credential</button><p role="alert" id="credential-error"></p></form>`);
 document.querySelector('#change-credential').addEventListener('submit',async event=>{event.preventDefault();const form=event.target,values=Object.fromEntries(new FormData(form)),button=event.submitter;button.disabled=true;try{await call('verify-pin','PUT',values);form.reset();document.querySelector('#detail').close();await onChanged();}catch(e){form.reset();document.querySelector('#credential-error').textContent=e.message;button.disabled=false;}finally{values.current=values.next=values.confirm='';}});
}
