import {escapeHTML as E,date,time} from './model.mjs';
export async function call(path,method='GET',body){const r=await fetch('/.netlify/functions/'+path,{method,credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const result=await r.json();if(!r.ok)throw Error(result.error||'Request was not accepted.');return result;}
export function securityCard(info,enabled){return `<section class="panel panel-body section-gap"><h2>Security</h2><p>Signed in as Daron · ${E(info?.session_status||'Session active')}</p><p>Last credential change: ${info?.password_changed_at?E(date(info.password_changed_at)):'Initial credential · change date not recorded'}</p><p>${info?.security_review_recommended?'Security review recommended':('Security review due: '+(info?.security_review_due_at?E(date(info.security_review_due_at)):'Not available'))}</p><button data-security-change ${enabled?'':'disabled'}>Change Password/PIN</button><p class="muted">Change it whenever you choose. We recommend a security review every 180 days; changes are not forced.</p></section>`;}
export async function manage(session){const data=await call('sessions?id='+encodeURIComponent(session.id)+'&action=manage-link');const url=new URL(data.url);if(url.origin!==location.origin||url.pathname!=='/manage-appointment.html'||!url.searchParams.get('token')||url.searchParams.get('session_id')!==session.id)throw Error('A valid signed appointment link was not returned.');location.assign(url.href);}
const ADD_SERVICES=[['implant-parasite-removal','Implant/Parasite Removal'],['follow-up-session','Follow-Up Session'],['heavy-duty-removal','Heavy Duty Removal'],['exorcism-session','Exorcism Session'],['emergency-removal-session','Emergency Removal Session'],['distance-energy-session','Distance Energy Session'],['energy-session-15-adult','15 Minute Energy Session (15 yrs + up)'],['energy-session-15-youth','15 Minute Energy Session (10 - 14 yrs)'],['energy-session-10-child','10 Minute Energy Session (9 yrs + down)'],['spiritual-coaching','Spiritual Coaching'],['house-cleansing-blessing','House Cleansing/Blessing In-Person']];
export function addAppointment(clients,openDialog,onChanged){
 const options=(clients||[]).slice().sort((a,b)=>String(a.full_name||'').localeCompare(String(b.full_name||''))).map(c=>`<option value="${E(c.id)}">${E(c.full_name)}</option>`).join('');
 const services=ADD_SERVICES.map(([id,label])=>`<option value="${id}">${E(label)}</option>`).join('');
 openDialog('Add appointment',`<p class="muted">Practitioner-only appointment. No payment, email, SMS, or Calendar event is created by this form.</p><form id="add-appointment"><label>Existing client<select name="client_id"><option value="">New or unlinked client</option>${options}</select></label><label>Client name<input name="client_name" required maxlength="160"></label><label>Service<select name="service" required>${services}</select></label><label>Date · Eastern<input name="session_date" type="date" required></label><label>Available time · Eastern<select name="slot_id" required disabled><option value="">Choose a date first</option></select></label><input type="hidden" name="session_time"><p class="muted" id="add-availability-status">Choose a date to load valid available slots.</p><button type="submit" class="gold">Create appointment</button><button type="button" data-close>Cancel</button><p role="alert" id="add-appointment-error"></p></form>`);
 const form=document.querySelector('#add-appointment'),dateInput=form.querySelector('[name="session_date"]'),slot=form.querySelector('[name="slot_id"]'),timeInput=form.querySelector('[name="session_time"]'),status=form.querySelector('#add-availability-status');
 form.querySelector('[name="client_id"]').addEventListener('change',event=>{const client=(clients||[]).find(c=>c.id===event.target.value);if(client)form.querySelector('[name="client_name"]').value=client.full_name||'';});
 dateInput.addEventListener('change',async()=>{slot.disabled=true;slot.innerHTML='<option value="">Loading available times…</option>';status.textContent='';try{const result=await call('availability?date='+encodeURIComponent(dateInput.value));const rows=(result.slots||[]).filter(s=>s.status==='available'&&!s.booked);slot.innerHTML='<option value="">Choose an available time</option>'+rows.map(s=>`<option value="${E(s.id)}" data-time="${E(s.time)}">${E(s.displayTime||s.time)}</option>`).join('');slot.disabled=rows.length===0;status.textContent=rows.length?'Only currently available slots are shown.':'No valid available slots for this date.';}catch(error){slot.innerHTML='<option value="">Availability unavailable</option>';status.textContent=error.message;}});
 slot.addEventListener('change',()=>{timeInput.value=slot.selectedOptions[0]?.dataset.time||'';});
 form.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{const values=Object.fromEntries(new FormData(form));await call('practitioner-create-session','POST',{...values,duration_minutes:60,request_id:crypto.randomUUID(),source:'manual_practitioner'});document.querySelector('#detail').close();await onChanged();}catch(error){document.querySelector('#add-appointment-error').textContent=error.message;button.disabled=false;}});
}
export function appointmentAction(action,session,openDialog,onChanged){
 const summary=`<p><strong>${E(session.client_name)}</strong><br>${E(session.service||'Service not recorded')}<br>${E(date(session.session_date))} · ${E(time(session.session_time))} Eastern</p>`;
 const requestId=crypto.randomUUID();
 const perform=(values)=>{openDialog(action==='Cancel'?'Confirm cancellation':'Confirm reschedule',summary+(action==='Reschedule'?`<p>New appointment: <strong>${E(date(values.new_date))} · ${E(time(values.new_time))} Eastern</strong></p>`:'')+`<p>This changes this appointment and its availability. Calendar and eligible client notices will follow the normal workflow. No refund is issued here.</p><form id="confirm-appointment"><button type="submit" class="gold">${action==='Cancel'?'Confirm cancellation':'Confirm reschedule'}</button><button type="button" data-close>Keep appointment unchanged</button><p role="alert" id="action-error"></p></form>`);
  document.querySelector('#confirm-appointment').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{await call('sessions?id='+encodeURIComponent(session.id),'PATCH',{p1:true,action:action.toLowerCase(),confirmed:true,request_id:requestId,expected_date:session.session_date,expected_time:session.session_time,...values});document.querySelector('#detail').close();await onChanged();}catch(e){document.querySelector('#action-error').textContent=e.message;button.disabled=false;}});
 };
 if(action==='Cancel'){perform({});return;}
 openDialog('Reschedule appointment',summary+`<form id="choose-appointment"><label>New date · Eastern<input name="new_date" type="date" required></label><label>New time · Eastern<input name="new_time" type="time" step="900" required></label><p class="muted">The Schedule display time zone does not change these Eastern booking inputs.</p><button type="submit">Review change</button><button type="button" data-close>Back</button></form>`);
 document.querySelector('#choose-appointment').addEventListener('submit',event=>{event.preventDefault();perform(Object.fromEntries(new FormData(event.target)));});
}
export function changeCredential(openDialog,onChanged){openDialog('Change your password',`<p>Use at least 12 characters. Saving signs out every existing dashboard session.</p><form id="change-credential"><label>Current password/PIN<input type="password" name="current" autocomplete="current-password" maxlength="256" required></label><label>New password<input type="password" name="next" autocomplete="new-password" minlength="12" maxlength="256" required></label><label>Confirm new password<input type="password" name="confirm" autocomplete="new-password" minlength="12" maxlength="256" required></label><button type="submit" class="gold">Change password and sign out</button><button type="button" data-close>Keep current credential</button><p role="alert" id="credential-error"></p></form>`);
 document.querySelector('#change-credential').addEventListener('submit',async event=>{event.preventDefault();const form=event.target,values=Object.fromEntries(new FormData(form)),button=event.submitter;button.disabled=true;try{await call('verify-pin','PUT',values);form.reset();document.querySelector('#detail').close();await onChanged();}catch(e){form.reset();document.querySelector('#credential-error').textContent=e.message;button.disabled=false;}finally{values.current=values.next=values.confirm='';}});
}
