import {call,securityCard,manage,appointmentAction,retryCalendar,changeCredential,addAppointment} from './actions.mjs';
import {paymentReconciliationPanel,bindPaymentReconciliation} from './payment-reconciliation.mjs';
import {contentWorkspace,contentDetails} from './content.mjs';
import * as M from './model.mjs';
import {sampleData} from './fixture.mjs';
import {loadData,clientDetail,login} from './api.mjs';
const E=M.escapeHTML,app=document.querySelector('#app'),dialog=document.querySelector('#detail');
const local=['localhost','127.0.0.1','[::1]'].includes(location.hostname);
const mutationsEnabled=!local&&['www.daronroyal.com','daronroyal.com','royal-energy-alchemy.netlify.app'].includes(location.hostname);
const preview=local&&new URLSearchParams(location.search).get('preview')==='1';
let scheduleFilter='All';
let scheduleZone='America/New_York';
let contentView='ideas',contentQuery='';
let data,area='today',includeQA=false,query='',page=0,scheduleView='Upcoming',messageFilter='All',month='',clientTab='Overview',selectedClient=null,dialogReturn=null,reconciliationFilters={clientName:'',date:'',from:'',to:''};
const icons={today:'M3 5h18v16H3z M7 2v6 M17 2v6 M3 11h18',clients:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 11a4 4 0 1 0 0-8a4 4 0 0 0 0 8 M17 4a4 4 0 0 1 0 8 M22 21v-2a4 4 0 0 0-3-4',schedule:'M3 5h18v16H3z M7 2v6 M17 2v6 M7 13h3 M14 13h3 M7 17h3',communications:'M3 5h18v14H3z M3 6l9 7 9-7',finance:'M3 7h18v14H3z M3 11h18 M6 16h4','content-studio':'M4 3h12l4 4v14H4z M8 11h8 M8 15h8 M8 7h4',system:'M12 3l8 4v6c0 5-8 8-8 8s-8-3-8-8V7z M8 12l3 3 5-6'};
const icon=n=>`<svg aria-hidden="true" viewBox="0 0 24 24"><path d="${icons[n]}"/></svg>`;
const badge=([label,cls])=>`<span class="badge ${E(cls)}">${E(label)}</span>`;
const initials=name=>String(name||'?').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const visibleClients=()=>data.clients.filter(c=>includeQA||!M.qa(c));
const visibleSessions=()=>data.sessions.filter(s=>includeQA||(!M.qa(s)&&!M.qa(data.clients.find(c=>c.id===s.client_id))));
const visibleMessages=()=>data.communications.filter(m=>includeQA||(!M.qa(m)&&!M.qa(data.clients.find(c=>c.id===m.client_id))));
const visibleLedger=()=>data.ledger.filter(l=>!M.silent(data.sessions.find(s=>s.id===l.related_session_id)||{})&&(includeQA||(!M.qa(l)&&!M.qa(data.clients.find(c=>c.id===l.client_id))&&!M.qa(data.sessions.find(s=>s.id===l.related_session_id)))));
const visiblePayments=()=>(data.payments||[]).filter(p=>includeQA||(!M.qa(p)&&!M.qa(data.clients.find(c=>c.id===p.client_id))&&!M.qa(data.sessions.find(s=>s.id===p.session_id))));
const clientName=id=>data.clients.find(c=>c.id===id)?.full_name||'Client not linked';
const rowBtn=(s,label='View')=>`<button data-session="${E(s.id)}" aria-label="${E(label+' '+s.client_name)}">${E(label)}</button>`;
function panel(title,body,link=''){return `<section class="panel"><div class="panel-head"><h2>${E(title)}</h2>${link}</div>${body}</section>`;}
function empty(text){return `<div class="empty">${E(text)}</div>`;}
function sessionRow(s,next=false){const shown=M.displayAppointment(s,area==='schedule'?scheduleZone:'America/New_York');return `<article class="session-row ${next?'next':''}"><div class="time">${E(shown.time)}<small>${E(shown.date)} · ${E(shown.zone)}</small></div><div><strong>${E(s.client_name)}</strong><small>${E(s.service||'Service not recorded')}</small>${M.silent(s)?'<small>Automatic messages off</small>':''}</div><div class="badges status-group">${badge(M.appointment(s))}${badge(M.payment(s))}${M.calendar(s,data.now)[0]==='Sync Error'?badge(M.calendar(s,data.now)):''}</div>${rowBtn(s)}${M.canJoin(s,data.now)?`<button class="join" data-review-action="Join Meet">${preview?'Join Meet · sample link':'Join Meet · disabled'}</button>`:''}</article>`;}
function revenue(compact=false){const f=M.finance(visibleLedger(),visibleSessions(),month,visiblePayments());let days=Array.from({length:4},(_,i)=>f.rows.filter(e=>e.entry_type==='payment'&&Math.min(3,Math.floor((Number(e.entry_date?.slice(8,10)||1)-1)/8))===i).reduce((a,e)=>a+Number(e.amount||0),0));let max=Math.max(...days,1);return `<div class="panel-body"><div class="revenue-grid"><div><small>Collected · ${E(month)}</small><strong>${M.money(f.collected)}</strong></div><div><small>Refunded</small><strong>${M.money(f.refunds)}</strong></div><div><small>Net collected</small><strong>${M.money(f.net)}</strong></div></div><div class="chart" role="img" aria-label="Weekly collections: ${E(days.map((v,i)=>'week '+(i+1)+' '+M.money(v)).join(', '))}">${days.map(v=>`<div class="bar-wrap"><span class="tiny-label">${M.money(v)}</span><div class="bar" style="height:${Math.max(2,v/max*65)}px"></div></div>`).join('')}</div><div class="chart-labels"><span>Days 1–8</span><span>9–16</span><span>17–24</span><span>25–end</span></div><p class="tiny-label revenue-disclaimer">Recorded payment and ledger collections only. Planner payment notes are excluded.${data.fullHistory?'':' Limited to loaded ledger records.'}</p>${compact?'':`<p>Known session balances: <strong>${M.money(f.balances)}</strong> · Stripe: ${M.money(f.stripe)} · Recorded manual: ${M.money(f.manual)}</p>`}</div>`;}
function issue(label,type){const symbol={payment:'$',waiver:'▤',calendar:'↻',communication:'✉',followup:'◷'}[type];return '<span class="issue issue-'+type+'"><span class="issue-icon" aria-hidden="true">'+symbol+'</span>'+E(label)+'</span>';}
function attentionIssues(s){let out=[];const p=M.payment(s),w=M.waiver(s),c=M.calendar(s,data.now);if(['amber','red'].includes(p[1]))out.push(issue(p[0],'payment'));if(w[0]==='Waiver Needed')out.push(issue(w[0],'waiver'));if(M.intake(s)[0]==='Intake Needed')out.push(issue('Intake Needed','waiver'));if(c[0]==='Sync Error')out.push(issue(c[0],'calendar'));return out.join('');}
function home(){
 const sessions=visibleSessions().slice().sort((a,b)=>M.stamp(a).localeCompare(M.stamp(b)));
 const today=sessions.filter(s=>s.session_date===M.dateKey(data.now)&&s.status!=='cancelled');
 const next=sessions.find(s=>M.future(s,data.now));
 const attention=sessions.filter(s=>M.needsAttention(s,data.now));
 const failed=visibleMessages().filter(m=>m.status==='failed');
 const fin=M.finance(visibleLedger(),sessions,month,visiblePayments());
 const followups=data.aftercare.filter(a=>a.status==='scheduled'&&a.scheduled_for&&a.scheduled_for<=data.now.toISOString()&&!M.silent(a)&&!M.silent(data.sessions.find(s=>s.id===a.session_id)||{})&&(includeQA||(!M.qa(a)&&!M.qa(data.clients.find(c=>c.id===a.client_id))&&!M.qa(data.sessions.find(s=>s.id===a.session_id)))));
 const recent=sessions.filter(s=>s.created_at).slice().sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,3);
 return `<div class="metrics"><div class="metric"><span class="eyebrow">Your day</span><strong>${today.length}</strong><small>Appointments · ${today.filter(s=>M.future(s,data.now)).length} remaining</small></div><div class="metric collections-primary"><span class="eyebrow">Verified collections this month</span><strong>${M.money(fin.collected)}</strong><small>Received payments + ledger · deduplicated</small></div><div class="metric"><span class="eyebrow">Planner/manual paid evidence</span><strong>${M.money(fin.evidenceTotal)}</strong><small>${E(month)} appointments · not verified revenue</small></div><div class="metric balances-secondary"><span class="eyebrow">Known balances</span><strong>${M.money(fin.balances)}</strong><small>${E(month)} sessions · planner evidence excluded</small></div><div class="metric"><span class="eyebrow">Needs attention</span><strong>${attention.length+failed.length+followups.length}</strong><small>Across appointments & messages</small></div></div>
 <div class="today-layout"><div class="today-schedule">${panel('Today’s appointments',`${next?`<div class="next-summary"><span class="live-dot" aria-hidden="true"></span><span>Next · <strong>${E(next.client_name)}</strong> ${next.session_date===M.dateKey(data.now)?'today':E(M.date(next.session_date))} at ${E(M.time(next.session_time))}</span><span class="muted">${E(M.calendar(next,data.now)[0])}</span></div>`:''}${today.length?today.map(s=>sessionRow(s,s.id===next?.id)).join(''):('<p class="muted panel-body">Your day is clear. Next appointments:</p>'+sessions.filter(s=>M.future(s,data.now)).slice(0,5).map(s=>sessionRow(s,s.id===next?.id)).join(''))}`,'<a href="#schedule">View schedule →</a>')}</div>
 <div class="today-attention">${panel('Needs attention',`${attention.slice(0,3).map(s=>`<div class="attention-item"><div><strong>${E(s.client_name)}</strong><div class="issue-list">${attentionIssues(s)}</div></div>${rowBtn(s,'Review')}</div>`).join('')}${failed.slice(0,1).map(m=>`<div class="attention-item"><div><strong>${E(clientName(m.client_id))}</strong><div class="issue-list">${issue('Message not delivered','communication')}</div></div><a href="#communications">Review →</a></div>`).join('')}${followups.slice(0,1).map(f=>`<div class="attention-item"><div><strong>${E(f.client_id?clientName(f.client_id):(f.client_name||'Unlinked follow-up'))}</strong><div class="issue-list">${issue('Follow-up Due','followup')}</div></div>${f.client_id?`<button class="link" data-client="${E(f.client_id)}">Review →</button>`:`<span class="muted">Client link missing</span>`}</div>`).join('')}${!attention.length&&!failed.length&&!followups.length?empty('Nothing needs attention in loaded records.'):''}`)}<div class="quiet-note"><span class="eyebrow">Client Records to Review</span><p>${visibleClients().filter(c=>c.tags?.includes('identity-linkage-pending')).length} descriptive identities to clarify</p><small>Identity cleanup only. Appointments stay scheduled.</small><a href="#clients">Review in Clients →</a></div></div>
 <div class="today-revenue">${panel('Revenue & payments',revenue(true),'<a href="#finance">Open Finance →</a>')}</div>
 <div class="today-activity"><details class="activity-disclosure"><summary>Recent bookings <span>${recent.length} latest records</span></summary>${recent.map(s=>`<div class="attention-item"><div><strong>${E(s.client_name)}</strong><p>${E(M.date(s.session_date))} · ${E(M.time(s.session_time))}</p></div>${rowBtn(s)}</div>`).join('')||empty('No creation dates in loaded records.')}</details><p class="tiny-label">Daily view · All times Eastern · Changes are disabled in this preview.</p></div></div>`;
}

function clients(){const matching=visibleClients().filter(c=>[c.full_name,c.email,c.phone].join(' ').toLowerCase().includes(query.toLowerCase()));const pages=Math.max(1,Math.ceil(matching.length/12));page=Math.min(page,pages-1);return `<div class="toolbar"><input id="client-search" type="search" aria-label="Search clients by name, email or phone" placeholder="Search name, email or phone" value="${E(query)}"><label class="check"><input id="qa-toggle" type="checkbox" ${includeQA?'checked':''}> Include QA/Test</label></div><p class="muted">${matching.length} clients · ${data.fullHistory?(preview?'Sample session counts':'Complete recorded session history'):'Session counts cover loaded records, not lifetime history'}</p><div class="directory">${matching.slice(page*12,page*12+12).map(c=>{const stats=M.clientStats(c,visibleSessions(),data.now);return `<article class="client-card"><div class="name-row"><span class="avatar">${E(initials(c.full_name))}</span><h2>${E(c.full_name)}</h2></div><div class="contact muted">${E(c.email||'Email not available')}<br>${E(c.phone||'Phone not available')}</div><p class="muted">${E(c.contact_completeness||'Contact details as recorded')}</p><dl><dt>Next visit</dt><dd>${stats.next?E(M.date(stats.next.session_date)):'None recorded'}</dd><dt>Last visit</dt><dd>${stats.last?E(M.date(stats.last.session_date)):'None recorded'}</dd><dt>Sessions${data.fullHistory?'':' loaded'}</dt><dd>${stats.count}</dd></dl><div class="badges">${badge(stats.next?['Upcoming','blue']:['No upcoming visit','muted'])}${stats.attention?badge(['Needs attention','amber']):''}${c.tags?.includes('identity-linkage-pending')?badge(['Identity review','purple']):''}</div><button data-client="${E(c.id)}">Open case file</button></article>`;}).join('')||empty('No clients match your search.')}</div><div class="paging"><button data-page="-1" ${page===0?'disabled':''}>Previous</button><small>Page ${page+1} of ${pages}</small><button data-page="1" ${page===pages-1?'disabled':''}>Next</button></div>`;}
function schedule(){
 let sessions=visibleSessions().filter(s=>scheduleView==='Past'?M.stamp(s)<M.dateKey(data.now)+'T'+M.clockKey(data.now)+':00'&&s.status!=='cancelled':scheduleView==='Cancelled'?s.status==='cancelled':scheduleView==='Needs Attention'?M.needsAttention(s,data.now):M.future(s,data.now));
 if(scheduleView==='Today')sessions=sessions.filter(s=>s.session_date===M.dateKey(data.now));
 if(['Next 7 Days','Next 30 Days'].includes(scheduleView)){const until=new Date(data.now);until.setDate(until.getDate()+(scheduleView==='Next 7 Days'?7:30));sessions=sessions.filter(s=>s.session_date<M.dateKey(until));}
 sessions=sessions.filter(s=>scheduleFilter==='All'||scheduleFilter==='Paid'&&s.payment_status==='paid'||scheduleFilter==='Payment Needed'&&M.payment(s)[0]==='Payment Needed'||scheduleFilter==='Payment Unverified'&&/unverified|not recorded|evidence/i.test(M.payment(s)[0])||scheduleFilter==='Meet Ready'&&M.canJoin(s,data.now)||scheduleFilter==='Website'&&['online','website'].includes(s.source)||scheduleFilter==='Planner / Manual'&&!['online','website'].includes(s.source)||scheduleFilter==='In Person'&&['in_person','in-person'].includes(s.location_type)||scheduleFilter==='Remote'&&['remote','distance'].includes(s.location_type));
 sessions.sort((a,b)=>M.stamp(a).localeCompare(M.stamp(b)));
 const weeks=new Map();for(const session of sessions){const d=M.displayAppointment(session,scheduleZone),monday=new Date(d.dateKey+'T12:00Z');monday.setUTCDate(monday.getUTCDate()-(monday.getUTCDay()+6)%7);const week=monday.toISOString().slice(0,10);if(!weeks.has(week))weeks.set(week,new Map());const days=weeks.get(week);if(!days.has(d.dateKey))days.set(d.dateKey,[]);days.get(d.dateKey).push(session);}
 return '<div class="toolbar"><div class="tabs">'+['Today','Next 7 Days','Next 30 Days','Upcoming','Past','Cancelled','Needs Attention'].map(v=>'<button data-schedule-view="'+v+'" aria-pressed="'+(v===scheduleView)+'">'+(v==='Upcoming'?'All Upcoming':v)+'</button>').join('')+'</div><label>Display time zone <select id="schedule-timezone">'+M.DISPLAY_ZONES.map(([id,label])=>'<option value="'+id+'" '+(id===scheduleZone?'selected':'')+'>'+label+'</option>').join('')+'</select></label><label>Appointment filter <select id="schedule-filter">'+['All','Paid','Payment Needed','Payment Unverified','Meet Ready','Website','Planner / Manual','In Person','Remote'].map(v=>'<option '+(v===scheduleFilter?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label class="check"><input id="qa-toggle" type="checkbox" '+(includeQA?'checked':'')+'> Include QA/Test</label></div><p class="view-intro">'+sessions.length+' appointments. Display time zone changes visualization only. Stored booking times and date-range filters remain Eastern.</p>'+([...weeks].map(([week,days],index)=>'<details class="panel schedule-week" '+(index<2?'open':'')+'><summary>Week of '+E(M.date(week))+' · '+[...days.values()].reduce((n,rows)=>n+rows.length,0)+' appointments</summary>'+[...days].map(([day,rows])=>'<h2 class="schedule-day">'+E(M.date(day))+' · '+rows.length+' appointments</h2>'+rows.map(row=>sessionRow(row)).join('')).join('')+'</details>').join('')||empty('No appointments in this view.'));
}

const messageType=t=>({meet_ready:'Meet-ready email',followup:'Follow-up',waiver:'Intake / waiver',payment_confirmation:'Payment confirmation',reminder:'Reminder',booking_confirmation:'Confirmation',manual:'Manual message',cancellation:'Cancellation',reschedule:'Reschedule',recommendation:'Recommendation'})[t]||'Customer communication';
function messageRows(messages){return messages.map(m=>`<tr><td data-label="Client">${E(clientName(m.client_id))}<small>${E(m.recipient_email||m.recipient||'Recipient not recorded')}</small></td><td data-label="Message">${E(m.subject||'No subject')}<small>${E(messageType(m.message_type))}</small></td><td data-label="Sent">${m.sent_at?E(new Date(m.sent_at).toLocaleString('en-US',{timeZone:'America/New_York'})):'Not sent'}</td><td data-label="Delivery">${badge([({sent:'Sent',delivered:'Delivered',failed:'Failed',pending:'Pending',queued:'Queued'})[m.status]||'Unknown',m.status==='failed'?'red':m.status==='delivered'?'green':'muted'])}${m.error_message?`<small>${E(m.error_message)}</small>`:''}</td></tr>`).join('');}
function communications(){const rows=visibleMessages().filter(m=>messageFilter==='All'||m.status===messageFilter);return `<div class="toolbar"><label>Delivery <select id="message-filter" aria-label="Delivery">${['All','sent','delivered','failed','pending'].map(v=>`<option value="${v}" ${v===messageFilter?'selected':''}>${v==='All'?v:v[0].toUpperCase()+v.slice(1)}</option>`).join('')}</select></label></div><div class="delivery-summary"><span><strong>${visibleMessages().length}</strong> messages</span><span><strong>${visibleMessages().filter(m=>m.status==='failed').length}</strong> need review</span><span>Delivery history · No messages sent from preview</span></div>${panel('Communications history',rows.length?`<div class="table-wrap"><table class="mobile-cards"><thead><tr><th>Client / recipient</th><th>Message / type</th><th>Sent · Eastern</th><th>Delivery</th></tr></thead><tbody>${messageRows(rows)}</tbody></table></div>`:empty('No messages match this view.'))}`;}
function ledgerRows(rows){return rows.map(r=>`<tr><td data-label="Date">${E(M.date(r.entry_date||r.created_at))}</td><td data-label="Client">${E(clientName(r.client_id))}</td><td data-label="Type">${E(({payment:'Payment',refund:'Refund',charge:'Charge',credit:'Credit'})[r.entry_type]||'Other ledger entry')}</td><td data-label="Method">${E(r.payment_method==='stripe'?'Stripe':r.payment_method||'Method not recorded')}</td><td data-label="Amount">${M.money(r.amount)}</td></tr>`).join('');}
function finance(){const f=M.finance(visibleLedger(),visibleSessions(),month,visiblePayments());const evidence=visibleSessions().filter(s=>f.evidence.some(e=>e.id===s.id));return `<div class="toolbar"><label>Period <input id="finance-month" type="month" value="${E(month)}"></label></div>${panel('Revenue & payments',revenue())}<div class="section-gap">${panel('Payment & ledger history',f.rows.length?`<div class="table-wrap"><table class="mobile-cards"><thead><tr><th>Date</th><th>Client</th><th>Type</th><th>Method</th><th>Amount</th></tr></thead><tbody>${ledgerRows(f.rows)}</tbody></table></div>`:empty('No recorded ledger entries for this period.'))}</div><div class="section-gap">${panel('Planner / manual paid evidence',`<div class="panel-body"><p><strong>${M.money(f.evidenceTotal)}</strong> · Planner ${M.money(f.plannerEvidence)} · Manual ${M.money(f.manualEvidence)} · ${f.evidence.length} explicit paid records</p><p class="help">Evidence is grouped by appointment month; receipt dates are not established. These notes are not verified collections, outstanding invoices or Stripe payments. They do not contribute to revenue totals.</p>${evidence.map(s=>`<div class="attention-item"><div><strong>${E(s.client_name)}</strong><small>${E(M.date(s.session_date))} · ${E(M.payment(s)[0])}</small></div>${rowBtn(s)}</div>`).join('')||empty('No planner evidence in loaded records.')}</div>`)}</div><p class="muted">Refunds and payment changes are unavailable in this read-only review. A future refund action must require fresh authentication and explicit amount/recipient confirmation.</p>`;}
function contentStudio(){return contentWorkspace(data.content,contentView,contentQuery);}
const reconcileDate=(base,days)=>{const d=new Date(`${base}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);};
function reconciliationRows(rows){if(!rows.length)return '<p id="reconcile-empty" class="muted">No matching rows.</p>';return `<div class="table-wrap"><table id="reconcile-table" class="mobile-cards"><thead><tr><th>Session ID</th><th>Client</th><th>Date / time</th><th>Status</th><th>Source</th><th>Calendar</th><th>Event ID</th><th>Meet URL</th></tr></thead><tbody>${rows.map(r=>`<tr><td data-label="Session ID">${E(r.session_id)}</td><td data-label="Client">${E(r.client_display_name||r.client_name)}<small>${E(r.client_id)}</small></td><td data-label="Date / time">${E(r.session_date)} · ${E(r.session_time)}</td><td data-label="Status">${E(r.status)}</td><td data-label="Source">${E(r.source)}</td><td data-label="Calendar">${E(r.google_calendar_status||'Not recorded')}</td><td data-label="Event ID">${r.has_google_calendar_event_id?'Yes':'No'}</td><td data-label="Meet URL">${r.has_google_meet_url?'Yes':'No'}</td></tr>`).join('')}</tbody></table></div>`;}
function reconciliationPanel(){return `<section class="panel section-gap"><div class="panel-head"><h2>Schedule reconciliation</h2></div><div class="panel-body"><p class="view-intro">Read-only appointment metadata for checking date, status, source and Calendar state. No changes are available.</p><div class="toolbar reconciliation-toolbar"><label>Client name<input id="reconcile-client" type="search" value="${E(reconciliationFilters.clientName)}" placeholder="Exact client name"></label><label>Exact date<input id="reconcile-date" type="date" value="${E(reconciliationFilters.date)}"></label><label>Start date<input id="reconcile-from" type="date" value="${E(reconciliationFilters.from)}"></label><label>End date<input id="reconcile-to" type="date" value="${E(reconciliationFilters.to)}"></label><button id="reconcile-run" class="gold" type="button">Run reconciliation</button></div><div class="tabs reconciliation-presets" aria-label="Reconciliation presets"><button type="button" data-reconcile-preset="sherry">Sherry Beckmann</button><button type="button" data-reconcile-preset="today">Today</button><button type="button" data-reconcile-preset="next14">Next 14 days</button></div><div id="reconcile-status" role="status" aria-live="polite" class="muted">Enter a filter or choose a preset, then run the read-only check.</div><div id="reconcile-results"></div></div></section>`;}
function system(){const d=data.diagnostics;return `${securityCard(data.security,mutationsEnabled)}<button id="refresh-health">Refresh read-only health checks</button><p class="view-intro">Read-only diagnostics. Configuration, saved workflow observations, and provider health are shown separately.</p><div class="system-cards">${(d?.services||[{name:'Diagnostics',status:'Degraded',detail:'Fictional preview; providers have not been checked.'}]).map(s=>`<article class="panel"><h2>${E(s.name)}</h2>${badge([s.status,s.status==='Healthy'?'green':s.status==='Attention Needed'?'amber':'muted'])}<p>${E(s.detail)}</p>${s.last_success_at?`<p class="muted">Last successful run: ${E(new Date(s.last_success_at).toLocaleString('en-US',{timeZone:'America/New_York'}))} Eastern</p>`:''}${s.mode?`<p>Mode: ${E(s.mode)}</p>`:''}</article>`).join('')}</div><section class="panel section-gap"><div class="panel-head"><h2>Workflow observations</h2></div><div class="panel-body"><p>Calendar failures: ${d?.counts.failedCalendar??'Not checked'} · Pending workflows: ${d?.counts.pendingWorkflows??d?.counts.stuckWorkflows??'Not checked'} · Failed communications: ${d?.counts.failedCommunications??'Not checked'}</p><p class="muted">Pending records do not prove a worker is stuck. Recent successful worker timestamps appear above when available.</p><details><summary>Technical Calendar states</summary>${visibleSessions().filter(s=>!M.silent(s)&&/error|failed/.test(s.google_calendar_status||'')).map(s=>`<p>${E(s.client_name)} · <code>${E(s.google_calendar_status)}</code></p>`).join('')||'<p>No saved Calendar failures.</p>'}</details></div></section>${reconciliationPanel()}${paymentReconciliationPanel()}<section class="panel section-gap"><div class="panel-head"><h2>Visibility & data coverage</h2></div><div class="panel-body"><label class="check"><input id="qa-toggle" type="checkbox" ${includeQA?'checked':''}> Include QA/Test records</label><p>${E(data.coverage)}</p><p>No operational or authentication data is stored in browser storage.</p></div></section>`;}

function render(){area=location.hash.slice(1).toLowerCase();if(!M.AREAS.some(a=>M.areaKey(a)===area))area='today';const title=area==='today'?'Good morning, Daron':M.AREAS.find(a=>M.areaKey(a)===area);app.innerHTML=`<aside class="sidebar" aria-label="Main navigation"><div class="brand"><div class="brand-mark" aria-hidden="true"><svg viewBox="0 0 80 70" width="64" height="58" fill="none" stroke="currentColor" stroke-width="1.4"><path d="M40 58C18 38 26 17 40 5c14 12 22 33 0 53Z"/><path d="M40 58C12 54 7 34 9 18c19 1 32 17 31 40ZM40 58c28-4 33-24 31-40-19 1-32 17-31 40Z"/><path d="M40 58C19 66 6 55 2 40c18-5 31 2 38 18Zm0 0c21 8 34-3 38-18-18-5-31 2-38 18Z"/><path d="M13 66h54"/></svg></div><strong>ROYAL ENERGY<br>ALCHEMY</strong><small>HEAL · ALIGN · RISE</small></div><nav class="nav">${M.AREAS.map(n=>`<a href="#${M.areaKey(n)}" ${area===M.areaKey(n)?'aria-current="page"':''}>${icon(M.areaKey(n))}${n}</a>`).join('')}</nav><div class="sidebar-bottom"><div class="moon" aria-hidden="true">☾</div><p>SPACE FOR WHAT MATTERS</p></div></aside><main class="main" id="workspace" tabindex="-1"><header class="topbar"><div><h1>${E(title)}</h1><p>${E(new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric',timeZone:'America/New_York'}).format(data.now))} · Eastern Time</p></div><div class="header-tools"><button data-review-action="Add appointment" class="gold">+ Add appointment</button><div class="profile"><span class="avatar">DR</span><span>Daron Royal<small style="display:block">Practitioner</small></span></div><button class="menu-button" aria-label="Open navigation" aria-expanded="false">☰</button></div></header><div class="review-banner"><span>${preview?'LOCAL DESIGN REVIEW · Fictional sample records · No production connection':(mutationsEnabled?'LIVE DATA · Practitioner dashboard':'LIVE DATA · Local read-only review · Changes disabled')}</span><a href="#system">View data coverage</a></div>${data.errors.map(err=>`<div class="error" role="alert">${E(err)}</div>`).join('')}<div id="view">${({today:home,clients,schedule,communications,finance,system,'content-studio':contentStudio})[area]()}</div><footer class="footer"><span>Royal Energy Alchemy · Practitioner workspace</span><span>Planner imports remain protected from automatic messages and Calendar sync.</span></footer></main>`;bind();}
async function runReconciliation(){const status=app.querySelector('#reconcile-status'),results=app.querySelector('#reconcile-results');if(!status||!results)return;const clientName=app.querySelector('#reconcile-client')?.value.trim()||'',date=app.querySelector('#reconcile-date')?.value||'',from=app.querySelector('#reconcile-from')?.value||'',to=app.querySelector('#reconcile-to')?.value||'';reconciliationFilters={clientName,date,from,to};const params=new URLSearchParams({reconcile:'true'});if(clientName)params.set('client_name',clientName);if(date)params.set('date',date);else{if(from)params.set('from',from);if(to)params.set('to',to);}status.textContent='Loading read-only reconciliation…';results.innerHTML='';try{const response=await fetch('/.netlify/functions/p1-read-model?'+params.toString(),{method:'GET',credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json','X-P1-Review':'read-only'}});if(response.status===401){status.textContent='Your dashboard session expired. Sign in again to run reconciliation.';return;}if(!response.ok){status.textContent='The reconciliation service is temporarily unavailable.';return;}const body=await response.json();const rows=Array.isArray(body.reconciliation)?body.reconciliation:[];status.textContent=rows.length?`${rows.length} matching row${rows.length===1?'':'s'}. Read-only results.`:'No matching rows.';results.innerHTML=reconciliationRows(rows);}catch{status.textContent='The reconciliation service could not be reached.';}}
function reconciliationPreset(name){const today=M.dateKey(data.now);if(name==='sherry')reconciliationFilters={clientName:'Sherry Beckmann',date:'',from:'',to:''};if(name==='today')reconciliationFilters={clientName:'',date:today,from:'',to:''};if(name==='next14')reconciliationFilters={clientName:'',date:'',from:today,to:reconcileDate(today,14)};render();runReconciliation();}
function bind(){app.querySelector('#refresh-health')?.addEventListener('click',async ev=>{ev.target.disabled=true;try{data=await loadData(includeQA,true);render();}catch(error){showLoadError(error);}});app.querySelector('#reconcile-run')?.addEventListener('click',runReconciliation);app.querySelectorAll('[data-reconcile-preset]').forEach(button=>button.addEventListener('click',()=>reconciliationPreset(button.dataset.reconcilePreset)));app.querySelector('#content-search')?.addEventListener('input',ev=>{contentQuery=ev.target.value;const pos=ev.target.selectionStart;render();const el=app.querySelector('#content-search');el.focus();el.setSelectionRange(pos,pos);});app.querySelector('#client-search')?.addEventListener('input',ev=>{query=ev.target.value;page=0;const pos=ev.target.selectionStart;render();const input=app.querySelector('#client-search');input.focus();input.setSelectionRange(pos,pos);});app.querySelector('#qa-toggle')?.addEventListener('change',async ev=>{includeQA=ev.target.checked;try{if(!preview)data=await loadData(includeQA);render();}catch(error){showLoadError(error);}});app.querySelector('#message-filter')?.addEventListener('change',ev=>{messageFilter=ev.target.value;render();});app.querySelector('#finance-month')?.addEventListener('change',ev=>{month=ev.target.value||M.dateKey(data.now).slice(0,7);render();});}
function openDialog(title,content){dialogReturn=document.activeElement;dialog.innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${E(title)}</h2><button data-close aria-label="Close details">✕</button></div><div class="dialog-body">${content}</div>`;if(!dialog.open)dialog.showModal();dialog.querySelector('[data-close]').focus();}
function sessionDetail(id){
 const s=data.sessions.find(r=>r.id===id);if(!s)return;
 const calendarHealthy=data.diagnostics?.services?.some(x=>x.name==='Google Calendar'&&x.status==='Healthy')===true;
 const retryAllowed=calendarHealthy&&['failed','error','retryable_error'].includes(String(s.google_calendar_status||'').toLowerCase())&&!['cancelled','completed','no_show'].includes(String(s.status||'').toLowerCase());
 const actionButtons=M.eligibleActions(s,data.now).filter(a=>a!=='View').map(a=>{
  if(a==='Retry Calendar')return `<button data-appointment-action="Retry Calendar" data-appointment-id="${E(s.id)}" ${mutationsEnabled&&retryAllowed?'':'disabled'}>${a}</button>`;
  if(['Manage','Reschedule','Cancel'].includes(a))return `<button data-appointment-action="${a}" data-appointment-id="${E(s.id)}" ${mutationsEnabled?'':'disabled'}>${a}</button>`;
  return `<button disabled>${E(a)}</button>`;
 }).join('');
 const clientButton=s.client_id?`<button data-client="${E(s.client_id)}">Open client case file</button>`:'';
 openDialog(s.client_name,`<p>${E(s.service||'Session')}</p><div class="badges">${badge(M.appointment(s))}${badge(M.payment(s))}${badge(M.waiver(s))}${badge(M.intake(s))}${badge(M.calendar(s,data.now))}</div><dl class="definition"><dt>Appointment</dt><dd>${E(M.date(s.session_date))} · ${E(M.time(s.session_time))} Eastern</dd><dt>Location</dt><dd>${E(s.location_type==='distance'?'Distance':s.location_type==='in_person'?'In person':'Not recorded')}</dd><dt>Source</dt><dd>${M.silent(s)?'Manual planner import':s.source==='online'?'Website booking':'Historical / manual'}</dd><dt>Client linkage</dt><dd>${E(clientName(s.client_id))}</dd><dt>Automation</dt><dd>${M.silent(s)?'Off — approved silent planner import':'Subject to payment, waiver and scheduling rules'}</dd></dl>${s.seller_notes?`<details><summary>Original practitioner notes</summary><p class="notes">${E(s.seller_notes)}</p></details>`:''}<div class="action-row">${clientButton}${actionButtons}</div><p class="muted">Manage opens a signed appointment link. Retry Calendar requires healthy live Calendar diagnostics and only requeues a failed session.</p>`);
}async function openClient(id){selectedClient=data.clients.find(c=>c.id===id);if(!selectedClient)return;clientTab='Overview';renderClient();if(!preview){const result=await clientDetail(id);if(selectedClient?.id!==id)return;selectedClient={...selectedClient,...result.record?.client,detail:result};renderClient();}}
function renderClient(){const c=selectedClient;if(!c)return;const detail=c.detail?.record;const sessions=M.forClient(visibleSessions(),c.id);const messages=(M.forClient(visibleMessages(),c.id)).map(m=>({...m,client_id:c.id}));const ledger=M.forClient(M.finance(visibleLedger(),visibleSessions(),'',visiblePayments()).rows,c.id);const relatives=detail?.relationships||data.relationships.filter(r=>r.client_id===c.id||r.related_client_id===c.id);const stats=M.clientStats(c,sessions,data.now);let content='';
 if(clientTab==='Overview')content=`<dl class="definition"><dt>Email</dt><dd>${E(c.email||'Not recorded')}</dd><dt>Phone</dt><dd>${E(c.phone||'Not recorded')}</dd><dt>Next appointment</dt><dd>${stats.next?E(M.date(stats.next.session_date)+' · '+M.time(stats.next.session_time)):'None recorded'}</dd><dt>Session history</dt><dd>${stats.count} ${detail?'total':'loaded'} sessions</dd><dt>Attention</dt><dd>${stats.attention?'Review upcoming payment / waiver / sync status':'No upcoming attention flags in loaded records'}</dd><dt>Recommendations</dt><dd>Not connected in this increment; no recommendations inferred.</dd></dl><h3>Practitioner timeline</h3><ul class="timeline">${sessions.slice().sort((a,b)=>M.stamp(b).localeCompare(M.stamp(a))).slice(0,4).map(s=>`<li>${E(s.service||'Session')} · ${E(M.appointment(s)[0])}<small>${E(M.date(s.session_date))}</small></li>`).join('')||'<li>No recorded sessions.</li>'}</ul>`;
 if(clientTab==='Sessions')content=sessions.map(s=>sessionRow(s)).join('')||empty('No linked sessions.');
 if(clientTab==='Communications')content=messages.length?`<table class="mobile-cards"><thead><tr><th>Recipient</th><th>Message</th><th>Sent</th><th>Delivery</th></tr></thead><tbody>${messageRows(messages)}</tbody></table>`:empty('No communications linked to this client ID.');
 if(clientTab==='Finance')content=ledger.length?`<table class="mobile-cards"><thead><tr><th>Date</th><th>Client</th><th>Type</th><th>Method</th><th>Amount</th></tr></thead><tbody>${ledgerRows(ledger)}</tbody></table>`:empty('No ledger entries linked to this client ID. Planner notes do not count as payments.');
 if(clientTab==='Notes')content=`<h3>Client notes</h3><p class="notes">${E(c.notes||'No recorded client notes.')}</p>${sessions.flatMap(s=>(s.session_notes||[]).map(n=>`<h3>${E(M.date(s.session_date))}</h3><p class="notes">${E(n.notes||n.content||'Note content unavailable')}</p>`)).join('')}<p class="muted">Browser-stored notes have not been migrated or combined with this record.</p>`;
 if(clientTab==='Related Clients')content=relatives.length?relatives.map(r=>`<p>${E(r.relationship_label||r.relationship_type)} · ${E(r.client?.full_name||'Related client')}</p>`).join(''):empty('No confirmed relationships. Descriptive family names are preserved in Notes for later linking.');
 openDialog(c.full_name,`<div class="case-summary"><span class="avatar">${E(initials(c.full_name))}</span><span>${E(c.email||'Email not recorded')}</span><span>· ${stats.count} ${detail?'total':'loaded'} sessions</span>${c.tags?.includes('identity-linkage-pending')?badge(['Identity review','purple']):''}</div><div class="tabs" aria-label="Client case file sections">${['Overview','Sessions','Communications','Finance','Notes','Related Clients'].map(t=>`<button data-client-tab="${t}" aria-pressed="${clientTab===t}">${t}</button>`).join('')}</div>${c.detail?.errors?.map(e=>`<p role="alert">${E(e)}</p>`).join('')||''}<section class="tab-content" aria-label="${clientTab}"><h3 class="case-section-heading">${clientTab}</h3>${content}</section>`);
}
document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.contentView){contentView=b.dataset.contentView;render();app.querySelector('[data-content-view="'+contentView+'"]')?.focus();}if(b.dataset.contentItem){const row=data.content?.[b.dataset.contentKind]?.find(r=>r.id===b.dataset.contentItem);if(row)openDialog(row.title||row.source_title||'Content details',contentDetails(row));}if(b.hasAttribute('data-close'))dialog.close();if(b.dataset.session)sessionDetail(b.dataset.session);if(b.dataset.client)openClient(b.dataset.client);if(b.dataset.clientTab){clientTab=b.dataset.clientTab;renderClient();dialog.querySelector(`[data-client-tab="${clientTab}"]`)?.focus();}if(b.dataset.scheduleView){scheduleView=b.dataset.scheduleView;render();app.querySelector(`[data-schedule-view="${scheduleView}"]`)?.focus();}if(b.dataset.page){page+=Number(b.dataset.page);render();}if(b.dataset.reviewAction&&(!mutationsEnabled||b.dataset.reviewAction!=='Add appointment')){document.querySelector('#notice').textContent=b.dataset.reviewAction+' is disabled in local review. No production action was taken.';setTimeout(()=>document.querySelector('#notice').textContent='',6500);}if(b.classList.contains('menu-button')){const side=document.querySelector('.sidebar');side.classList.toggle('open');b.setAttribute('aria-expanded',String(side.classList.contains('open')));if(side.classList.contains('open'))side.querySelector('a').focus();}});
dialog.addEventListener('close',()=>{if(dialogReturn?.isConnected)dialogReturn.focus();else document.querySelector('#workspace')?.focus();});
dialog.addEventListener('keydown',ev=>{if(ev.key!=='Tab')return;const els=[...dialog.querySelectorAll('button:not(:disabled),a[href],input,select,[tabindex="0"]')];const first=els[0],last=els.at(-1);if(ev.shiftKey&&document.activeElement===first){ev.preventDefault();last.focus();}else if(!ev.shiftKey&&document.activeElement===last){ev.preventDefault();first.focus();}});
document.addEventListener('keydown',ev=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(ev.key)&&ev.target.matches('[data-client-tab]')){ev.preventDefault();const tabs=[...dialog.querySelectorAll('[data-client-tab]')],index=tabs.indexOf(ev.target);const next=ev.key==='Home'?0:ev.key==='End'?tabs.length-1:(index+(ev.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].click();}if(ev.key==='Escape'){document.querySelector('.sidebar')?.classList.remove('open');document.querySelector('.menu-button')?.setAttribute('aria-expanded','false');}});
window.addEventListener('resize',()=>{if(dialog.open)dialog.querySelector('[data-client-tab][aria-pressed=true]')?.scrollIntoView({block:'nearest',inline:'nearest'});});
window.addEventListener('hashchange',()=>{page=0;render();document.querySelector('#workspace').focus();});
function renderLogin(message='Your dashboard session has expired. Sign in again.'){app.innerHTML='<main class="main"><section class="panel panel-body"><h1>Sign in, Daron</h1><p>Secure access to your practitioner dashboard.</p><form id="sign-in"><label for="admin-pin">Dashboard password</label><input id="admin-pin" type="password" autocomplete="current-password" required><button class="gold" type="submit">Sign in</button><p id="login-error" role="alert">'+E(message)+'</p></form></section></main>';app.querySelector('#sign-in').addEventListener('submit',async ev=>{ev.preventDefault();const input=app.querySelector('#admin-pin');const pin=input.value;input.value='';try{await login(pin);await start();}catch(e){app.querySelector('#login-error').textContent=e.message;}});app.querySelector('#admin-pin').focus();}
function showLoadError(error){if(error.status===401||error.status===403){renderLogin(error.status===403?'Dashboard access requires a fresh sign-in.':'Your dashboard session has expired. Sign in again.');return;}app.innerHTML='<main class="main"><section class="panel panel-body"><h1>Dashboard unavailable</h1><p role="alert">'+E(error.message)+'</p><p>Retry the read-only bootstrap. No sample records were substituted.</p><button id="retry-bootstrap" class="gold" type="button">Retry</button></section></main>';app.querySelector('#retry-bootstrap').addEventListener('click',()=>{app.innerHTML='<p role="status">Loading your workspace…</p>';start();});}
async function start(){try{data=preview?sampleData():await loadData(includeQA);month=M.dateKey(data.now).slice(0,7);render();}catch(error){showLoadError(error);}}
await start();

document.addEventListener('change',event=>{if(event.target.id==='schedule-timezone'){scheduleZone=event.target.value;render();document.querySelector('#schedule-timezone')?.focus();}});

document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button||!mutationsEnabled)return;try{if(button.dataset.reviewAction==='Add appointment'){const calendarHealthy=data.diagnostics?.services?.some(s=>s.name==='Google Calendar'&&s.status==='Healthy')===true;addAppointment(data.clients,openDialog,start,data.now,calendarHealthy);return;}if(button.hasAttribute('data-security-change'))changeCredential(openDialog,start);if(button.dataset.appointmentAction){const session=data.sessions.find(s=>s.id===button.dataset.appointmentId);if(!session)return;if(button.dataset.appointmentAction==='Manage'){button.disabled=true;await manage(session);}else if(button.dataset.appointmentAction==='Retry Calendar'){button.disabled=true;await retryCalendar(session,start);}else appointmentAction(button.dataset.appointmentAction,session,openDialog,start);}}catch(e){document.querySelector('#notice').textContent=e.message;button.disabled=false;}});

document.addEventListener('change',event=>{if(event.target.id==='schedule-filter'){scheduleFilter=event.target.value;render();document.querySelector('#schedule-filter')?.focus();}});

document.addEventListener('click',event=>{if(event.target.hasAttribute('data-load-tiktok')){if(preview){document.querySelector('#tiktok-container').textContent='TikTok is not loaded in fictional preview.';return;}document.querySelector('#tiktok-container').innerHTML='<iframe class="tiktok-frame" title="Daron Royal TikTok profile videos" sandbox="allow-scripts allow-popups allow-popups-to-escape-sandbox" referrerpolicy="no-referrer" src="/.netlify/functions/p1-read-model?embed=tiktok"></iframe>';event.target.disabled=true;}});
function paymentSettingsPanel(){return `<section id="payment-settings-panel" class="panel section-gap"><div class="panel-head"><h2>Public payment destinations</h2></div><div class="panel-body"><p>Manage only client-facing payment instructions. No card, bank, CVV, password, token, or provider login data is stored here.</p><button id="open-payment-settings" type="button">Manage payment methods</button></div></section>`;}
async function openPaymentSettings(){let result;try{result=await call('practitioner-payment-settings');}catch(error){document.querySelector('#notice').textContent=error.message;return;}const settings=result.settings||{};const field=(provider,label)=>{const value=settings[provider]||{};const key=provider==='cash_app'?'cash_app':provider;return `<fieldset><legend>${E(label)}</legend><label><input type="checkbox" name="${key}_enabled" ${value.enabled?'checked':''}> Enabled</label><label>Public label<input name="${key}_label" maxlength="120" value="${E(value.label||'')}"></label><label>Public destination/instructions<textarea name="${key}_destination" maxlength="1000">${E(value.destination||'')}</textarea></label></fieldset>`;};openDialog('Payment method settings',`<p class="muted">Only safe public payment destinations and instructions are allowed. Never enter credentials, card data, bank data, PINs, passwords, or tokens.</p><form id="payment-settings-form">${field('venmo','Venmo')}${field('cash_app','Cash App')}${field('paypal','PayPal')}${field('zelle','Zelle')}${field('other','Other / manual')}<button class="gold" type="submit">Save payment settings</button><button type="button" data-close>Cancel</button><p id="payment-settings-error" role="alert"></p></form>`);document.querySelector('#payment-settings-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.target,button=event.submitter;button.disabled=true;try{const values=Object.fromEntries(new FormData(form));for(const provider of ['venmo','cash_app','paypal','zelle','other'])values[`${provider}_enabled`]=form.elements[`${provider}_enabled`].checked;await call('practitioner-payment-settings','PATCH',values);dialog.close();document.querySelector('#notice').textContent='Payment settings saved.';}catch(error){document.querySelector('#payment-settings-error').textContent=error.message;button.disabled=false;}});}
const paymentSettingsObserver=new MutationObserver(()=>{if(area!=='system'||!mutationsEnabled)return;const view=document.querySelector('#view');if(!view||view.querySelector('#payment-settings-panel'))return;view.insertAdjacentHTML('beforeend',paymentSettingsPanel());view.querySelector('#open-payment-settings')?.addEventListener('click',openPaymentSettings);});
paymentSettingsObserver.observe(app,{childList:true,subtree:true});
if(area==='system'&&mutationsEnabled){const view=document.querySelector('#view');if(view&&!view.querySelector('#payment-settings-panel')){view.insertAdjacentHTML('beforeend',paymentSettingsPanel());view.querySelector('#open-payment-settings')?.addEventListener('click',openPaymentSettings);}}
