import {escapeHTML as E,date} from './model.mjs';
const labels={social_post:'Social post',video:'Video',newsletter:'Newsletter',blog:'Blog',faq:'FAQ',draft:'Draft',review:'In review',approved:'Approved',published:'Published',archived:'Archived',high:'High priority',medium:'Medium priority',low:'Low priority'};
export const contentLabel=v=>labels[v]||String(v||'Not specified').replaceAll('_',' ');
export function contentWorkspace(content,view='ideas',query=''){
 const d=content||{ideas:[],drafts:[],sources:[],errors:['Content sources have not been loaded.']};
 const rows=(d[view]||[]).filter(r=>[r.title,r.source_title,r.topic,r.summary,r.source_summary].join(' ').toLowerCase().includes(query.toLowerCase())).slice().sort((a,b)=>(b.updated_at||b.created_at||'').localeCompare(a.updated_at||a.created_at||''));
 return `<p class="view-intro">A calm place to review ideas, saved drafts and source material. Your production content is read-only.</p><div class="content-summary">${[['ideas','Ideas'],['drafts','Saved drafts'],['sources','Sources']].map(([k,label])=>`<article class="panel panel-body"><small>${label}</small><h2>${(d[k]||[]).length}</h2></article>`).join('')}</div><div class="toolbar section-gap"><div class="tabs" aria-label="Content Studio views">${[['ideas','Ideas'],['drafts','Draft library'],['sources','Sources'],['tiktok','TikTok Library']].map(([k,label])=>`<button data-content-view="${k}" aria-pressed="${view===k}">${label}</button>`).join('')}</div><input id="content-search" type="search" aria-label="Search Content Studio" placeholder="Search ${view}" value="${E(query)}"></div><div class="action-row"><button disabled title="Content editing awaits separate approval">New idea</button><button disabled title="Generation awaits a constrained workflow">Generate draft</button><button disabled title="Publishing is not enabled">Publish</button></div><p class="muted">Editing, generation and publishing are disabled. Saved “Published” status does not verify a live public post.</p>${(d.errors||[]).map(e=>`<p role="alert">${E(e)}</p>`).join('')}${view==='tiktok'?`<section class="panel panel-body"><h2>@daronroyal · TikTok Library</h2><p>${(d.tiktok||[]).length} saved video references. The official profile embed may show up to ten recent videos; it is not a complete imported feed.</p><a href="https://www.tiktok.com/@daronroyal" target="_blank" rel="noopener noreferrer">Open on TikTok</a><p class="muted">TikTok controls embed availability. Automatic metadata ingestion requires an approved Display API connection. No posting is enabled.</p><button data-load-tiktok>Load TikTok profile videos</button><div id="tiktok-container"></div></section>`:''}<div class="directory content-directory">${rows.map(r=>`<article class="panel panel-body"><p class="muted">${E(contentLabel(r.content_type||r.source_type))}</p><h2>${E(r.title||r.source_title||'Untitled')}</h2><div class="badges">${r.status?`<span class="badge ${r.status==='approved'?'green':'muted'}">${E(contentLabel(r.status))}</span>`:''}${r.priority?`<span class="badge muted">${E(contentLabel(r.priority))}</span>`:''}</div><p class="content-excerpt">${E(r.summary||r.source_summary||r.topic||'No summary recorded.')}</p>${r.scheduled_date?`<p class="muted">Planned: ${E(date(r.scheduled_date))} · no automatic publishing</p>`:''}<button data-content-item="${E(r.id)}" data-content-kind="${view}">Read details</button></article>`).join('')||`<section class="panel panel-body"><h2>No ${E(view)} ${query?'match your search':'recorded'}</h2><p>${query?'Try another search.':'This is the current saved content collection. No sample content was substituted.'}</p></section>`}</div>`;
}
export function contentDetails(row){const body=row.draft_content;return `<p class="muted">${E(contentLabel(row.content_type||row.source_type))} · Read only</p>${row.status?`<p>Saved status: ${E(contentLabel(row.status))}</p>`:''}<p class="notes">${E(row.summary||row.source_summary||row.topic||'No summary recorded.')}</p>${body?`<h3>Saved draft</h3><pre class="content-body">${E(typeof body==='string'?body:JSON.stringify(body,null,2))}</pre>`:''}${row.source_url?`<p class="notes">Source address: ${E(row.source_url)}</p>`:''}<p class="muted">Changes and publishing remain disabled.</p>${/^https:\/\/www\.tiktok\.com\/@daronroyal\/video\/\d+/.test(row.source_url||'')?`<a href="${E(row.source_url)}" target="_blank" rel="noopener noreferrer">Open on TikTok</a>`:''}`;}
