import {IMPORT} from './model.mjs';
export function sampleData(){
 const clients=[['c1','Emma Carter','emma@example.com'],['c2','James Riley','james@example.com'],['c3','Ava Martinez','ava@example.com'],['c4','Daniel Kim',null],['c5','Ariel’s boys',null],['c6','Ava Martinez','ava.other@example.com'],['cq','[QA] Review fixture','qa@example.com']].map(([id,full_name,email])=>({id,full_name,email,phone:null,status:'active',source:id==='cq'?'qa':'manual',tags:id==='c4'||id==='c5'?['identity-linkage-pending']:[],notes:id==='c5'?'Descriptive identity. Family relationship not yet verified.':'Contact details and notes shown here are fictional preview data.'}));
 const s=(id,client_id,day,at,extra={})=>({id,client_id,client_name:clients.find(c=>c.id===client_id).full_name,service:'Energy healing',session_date:day,session_time:at+':00',created_at:'2026-09-01T12:00:00Z',status:'confirmed',payment_status:'paid',amount_due:100,amount_paid:100,source:'online',waiver_completed:true,location_type:'distance',google_calendar_status:'synced',...extra});
 const sessions=[s('s1','c1','2026-09-14','09:30',{status:'completed',service:'Monthly maintenance'}),s('s2','c2','2026-09-14','12:00',{google_meet_url:'https://meet.google.com/abc-defg-hij'}),s('s3','c3','2026-09-14','16:00',{service:'Follow-up',payment_status:'unpaid',amount_paid:0,waiver_completed:false,google_calendar_status:'not_requested'}),s('s4','c4','2026-09-14','18:00',{service:'Planner appointment',source:IMPORT,amount_due:null,amount_paid:0,payment_status:'unpaid',waiver_completed:null,google_calendar_status:'not_requested',seller_notes:'Paid noted: Yes. Original description preserved. Automatic communications suppressed.'}),s('s5','c2','2026-09-15','10:00',{google_calendar_status:'retryable_error'}),s('s6','c5','2026-09-16','12:30',{source:IMPORT,payment_status:'unpaid',amount_due:null,amount_paid:0,waiver_completed:null,google_calendar_status:'not_requested'}),s('s7','c1','2026-09-08','10:00',{status:'completed',session_notes:[{notes:'Client requested a quieter session. Fictional preview note.'}]}),s('s8','c6','2026-09-10','14:00',{status:'cancelled',payment_status:'refunded'}),s('sq','cq','2026-09-14','14:00',{source:'qa',is_test:true})];
 const ledger=[{id:'p1',client_id:'c1',session_id:'s1',entry_type:'payment',amount:100,payment_method:'stripe',entry_date:'2026-09-14'},{id:'p2',client_id:'c2',session_id:'s2',entry_type:'payment',amount:100,payment_method:'stripe',entry_date:'2026-09-14'},{id:'p3',client_id:'c1',session_id:'s7',entry_type:'payment',amount:70,payment_method:'cash',entry_date:'2026-09-08'},{id:'p4',client_id:'c6',session_id:'s8',entry_type:'refund',amount:90,payment_method:'stripe',entry_date:'2026-09-10'}];
 const communications=[{id:'m1',client_id:'c2',recipient_email:'james@example.com',message_type:'meet_ready',subject:'Your session link is ready',status:'sent',sent_at:'2026-09-14T13:00:00Z'},{id:'m2',client_id:'c3',recipient_email:'ava@example.com',message_type:'waiver',subject:'Complete your intake before your session',status:'failed',error_message:'Sample delivery failure: mailbox unavailable',sent_at:'2026-09-14T12:30:00Z'},{id:'m3',client_id:'c1',recipient_email:'emma@example.com',message_type:'followup',subject:'After your session',status:'delivered',sent_at:'2026-09-11T16:00:00Z'}];
 return {clients,sessions,ledger,communications,relationships:[],aftercare:[{id:'a1',client_id:'c1',session_id:'s7',scheduled_for:'2026-09-14T12:00:00Z',status:'scheduled',followup_type:'72hr'}],now:new Date('2026-09-14T15:15:00Z'),preview:true,errors:[],coverage:'Synthetic review data — not production',fullHistory:true};
}
